dataVisualization/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    #url(r'^polls/', include('polls.urls')),
    url(r'^dv/', include('dv.urls')),
    url(r'^admin/', admin.site.urls),
]

dv/urls.py
from django.conf.urls import url

from . import views

app_name = 'dv'
urlpatterns = [
    url(r'^$', views.index, name='index'),
]

polls/urls.py
from django.conf.urls import include, url
from rest_framework import routers

from . import views

router = routers.DefaultRouter()

app_name = 'polls'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^(?P<question_id>[0-9]+)/$', views.detail, name='detail'),
    url(r'^(?P<question_id>[0-9]+)/results/$', views.results, name='results'),
    url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
    url(r'^test/$', views.test, name='test'),
]

dv/models.py
from __future__ import unicode_literals

from django.db import models
from django.utils import timezone

import datetime

# Create your models here.
class CrimeRecord(models.Model):
    place = models.CharField(max_length=200)
    incident = models.CharField(max_length=200)
    year = models.IntegerField()
    quarter = models.CharField(max_length=200)
    month = models.IntegerField()
    times = models.IntegerField()

class Incident(models.Model):
    incident = models.CharField(max_length=200)

class Place(models.Model):
    place = models.CharField(max_length=200)
    setted = models.BooleanField(default = True)

class Month(models.Model):
    month = models.CharField(max_length=200)
    setted = models.BooleanField(default = True)

class Year(models.Model):
    year = models.CharField(max_length=200)
    setted = models.BooleanField(default = True)

polls/models.py
from __future__ import unicode_literals

from django.db import models
from django.utils import timezone

import datetime

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    
    def __str__(self):
        return self.question_text
    
    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)    


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    def __str__(self):
        return self.choice_text    

dv/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse

from models import *
from fc import *

import operator

def _get_frequency_of_crime_(incident_name):
    qs = CrimeRecord.objects.filter(incident = incident_name)
    
    for place in Place.objects.filter(setted = False):
        qs = qs.exclude(place = place.place)
    for year in Year.objects.filter(setted = False):
        qs = qs.exclude(year = int(year.year))
    for month in Month.objects.filter(setted = False):
        qs = qs.exclude(month = int(month.month))
    
    cnt = 0
    for rec in qs:
        cnt += rec.times

    return cnt

def get_frequency_of_crime(incidents):
    res = []
    for incident in incidents:
        res.append(_get_frequency_of_crime_(incident.incident))
    return res

def set_flag(request):
    ex_places = Place.objects.all()
    ex_years = Year.objects.all()
    ex_months = Month.objects.all()
    
    for key in request.POST:
        if 'place' in key:
            ex_places = ex_places.exclude(place = request.POST[key])
            tmp = Place.objects.get(place = request.POST[key])
            tmp.setted = True
            tmp.save()
        
        if 'year' in key:
            ex_years = ex_years.exclude(year = request.POST[key])
            tmp = Year.objects.get(year = request.POST[key])
            tmp.setted = True
            tmp.save()
        
        if 'month' in key:
            ex_months = ex_months.exclude(month = request.POST[key])
            tmp = Month.objects.get(month = request.POST[key])
            tmp.setted = True
            tmp.save()
    
    for obj in ex_places:
        obj.setted = False
        obj.save()
    
    for obj in ex_years:
        obj.setted = False
        obj.save()
        
    for obj in ex_months:
        obj.setted = False
        obj.save()    

# Create your views here.
def index(request):
    if len(CrimeRecord.objects.all()) == 0:
        setup()
    
    if request.method == 'POST':
        set_flag(request)
    
    incidents = list(Incident.objects.all())
    places = list(sorted(Place.objects.all(),key=operator.attrgetter('place')))
    years = list(sorted(Year.objects.all(),key=operator.attrgetter('year')))
    months = list(Month.objects.all())
    
    context = {'incidents' : incidents, 
               'places' : places, 
               'years' : years, 
               'months' : months, 
               'res' : get_frequency_of_crime(incidents)}
    
    return render(request, 'dv/index.html', context)

polls/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse

from .models import Choice, Question

def test(request):
    test_data=[5,5,5]
    context = {'test_data': test_data}
    return render(request, 'polls/test.html', context)

def index(request):
    latest_question_list = Question.objects.order_by('-pub_date')[:5]
    context = {'latest_question_list': latest_question_list}
    return render(request, 'polls/index.html', context)

def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/detail.html', {'question': question})

def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/results.html', {'question': question})

def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

dataVisualization/polls/templates/polls/index.html
{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

dv/templates/dv/index.html
<!DOCTYPE HTML>
<html>
	<head>
		<title>Crime Data Visualization</title>
		<script src="https://code.highcharts.com/highcharts.js"></script>
		<script src="https://code.jquery.com/jquery-1.11.0.min.js"></script>
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">
		<script src="https://npmcdn.com/tether@1.2.4/dist/js/tether.min.js"></script>
		<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js" integrity="sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn" crossorigin="anonymous"></script>

	</head>
	<body>

		<div class="container">
			<div class="row">
				<div class="page-header">
					<h1>Crime Data Visualization</h1>
				</div>
				
				<script>
					var incidents = [];
					var res = [];
				</script>
				
				{% for type in incidents %}
					<script>
						var type = "{{ type.incident }}";
						incidents.push(type);
					</script>
				{% endfor %}
				
				{% for freq in res %}
					<script>
						var tmp = "{{ freq }}";
						res.push(parseInt(tmp));
					</script>
				{% endfor %}

				<div id="container" style="width:100%; height:400px;"></div>
				    <div class="btn-group" data-toggle="buttons">
				        <label class="btn btn-primary active" onclick="chartfunc()" ><input type="radio" name="mychart" id="column" value="column" checked />Column</label>
				        <label class="btn btn-primary" onclick="chartfunc()" ><input type="radio" name="mychart" id="bar" value="bar" />Bar</label>
				        <label class="btn btn-primary" onclick="chartfunc()" ><input type="radio" name="mychart" id="pie" value="pie" />Pie</label>
				    </div>
				</div>
			</div>

			<form action="{% url 'dv:index' %}" method="post">
			
			{% csrf_token %}
			    <div class="row">
				    <div class="col-sm-4">
					    <div class="card">
						    <h3 class="card-title">Places</h3>
						    <div class="card-block" style="height:200px; overflow:auto;">
							    
							    {% for place in places %}
								{% if place.setted %}
								<input type="checkbox" name="place{{ forloop.counter }}" value="{{ place.place }}" checked >{{ place.place }}<br>
								{% else %}
								<input type="checkbox" name="place{{ forloop.counter }}" value="{{ place.place }}" >{{ place.place }}<br>
								{% endif %}
							    {% endfor %}
							    
						    </div>
					    </div>
				    </div>

				    <div class="col-sm-4">
					    <div class="card">
					        <h3 class="card-title">Years</h3>
						    <div class="card-block" style="height:200px; overflow:auto;">
							    
							    {% for year in years %}
								{% if year.setted %}
								<input type="checkbox" name="year{{ forloop.counter }}" value="{{ year.year }}" checked >{{ year.year }}<br>
								{% else %}
								<input type="checkbox" name="year{{ forloop.counter }}" value="{{ year.year }}">{{ year.year }}<br>
								{% endif %}
							    {% endfor %}
							    
						    </div>
					    </div>
				    </div>

				    <div class="col-sm-4">
					    <div class="card">
					        <h3 class="card-title" >Month</h3>
						    <div class="card-block" style="height:200px; overflow:auto;">
							    
							    {% for month in months %}
								{% if month.setted %}
								<input type="checkbox" name="month{{ forloop.counter }}" value="{{ month.month }}" checked >{{ month.month }}<br>
								{% else %}
								<input type="checkbox" name="month{{ forloop.counter }}" value="{{ month.month }}">{{ month.month }}<br>
								{% endif %}
							    {% endfor %}
						
						    </div>
					    </div>
				    </div>
				    <br>
			    </div>
			    <input class="btn btn-primary" type="submit" style="width:100px; display:block; margin:0 auto;" value="Set">
			</form>
		</div>
		
		<script>
			$(function () {
				Highcharts.setOptions({
        				chart: {
            					backgroundColor: {
                					linearGradient: [0, 235, 500, 500],
                					stops: [
                    						[0, 'rgb(235, 245, 235)'],
                    						[1, 'rgb(240, 140, 155)']
                    					]
            					},
            					borderWidth: 5,
            					plotBackgroundColor: 'rgba(0, 0, 0, .9)',
            					plotShadow: true,
            					plotBorderWidth: 5
        				}
    				});

			// Create the charts

			var options = {
			    	chart: {
			       		events: {
			            		drilldown: function (e) {
			                		if (!e.seriesOptions) {
								var chart = this;

			                    			chart.showLoading('Loading ...');

			                    			setTimeout(function () {
			                        		    chart.hideLoading();
			                       				chart.addSeriesAsDrilldown(e.point, series);
			                    		    }, 1000);
			                	}
			            	}
			        },
			        plotBorderWidth: 0
			    },

			    title: {
			        	text: 'Three Types of Charts',
			    },
			    //
			    subtitle: {
			            	text: 'Column, Bar and Pie'
			    },
			    //
			    xAxis: {
			            	categories: incidents,
			    },
			    //
			    yAxis: {

        				title: {
            					text: 'Frequency'
        				}
			    },
			    //
			    legend: {
			        	enabled: true,
			    },
			    //
			    plotOptions: {
			        	series: {
			            		pointPadding: 0.2,
			            		borderWidth: 0,
			            		dataLabels: {
			                		enabled: true
			            		}
			   		},
			        	pie: {
			            		plotBorderWidth: 0,
			            		allowPointSelect: true,
			            		cursor: 'pointer',
			            		size: '100%',
			            		dataLabels: {
			                		enabled: true,
			                		format: '{point.name}: <b>{point.y}</b>'
			            		}
			        	}
			    },
			    //
			    series: [{
    					name: 'Crime Frequency',
    					data: res
			    }],
			    //
			    drilldown: {
			        	series: []
			    }
			};

			// Column chart
			options.chart.renderTo = 'container';
			options.chart.type = 'column';
			var chart1 = new Highcharts.Chart(options);

			chartfunc = function(){
				var column = document.getElementById('column');
				var bar = document.getElementById('bar');
				var pie = document.getElementById('pie');


				if(column.checked)
			    	{
			        	options.chart.renderTo = 'container';
			        	options.chart.type = 'column';
			        	var chart1 = new Highcharts.Chart(options);
			    	}
				else if(bar.checked)
			    	{
			        	options.chart.renderTo = 'container';
			        	options.chart.type = 'bar';
			        	var chart1 = new Highcharts.Chart(options);
			    	}
				else
			    	{
			        	options.chart.renderTo = 'container';
			        	options.chart.type = 'pie';
			        	var chart1 = new Highcharts.Chart(options);
			    	}

			}

				$('#change_chart_title').click(function(){
			    		var new_title = $('#chart_title').val();
			    		var chart = $('#container').highcharts();
			    		chart.setTitle({ text: new_title });

			    		alert('Chart title changed to '+new_title+' !');

				});
			});
		</script>
	</body>
</html>

polls/templates/polls/detail.html
<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br />
{% endfor %}
<input type="submit" value="Vote" />
</form>

polls/templates/polls/index.html
<!DOCTYPE HTML>
<html> 
	<head> 
		<title>Test Chart</title> 
		<script src="http://code.highcharts.com/highcharts.js"></script>
		<script src="http://code.jquery.com/jquery-1.11.0.min.js"></script>
	</head>
	<body> 
		<p id="demo">Test</p>
		{% if latest_question_list %}
    			<ul>
    			{% for question in latest_question_list %}
        			<li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
				<script>
					var a = "{{ question.question_text }}"; 
				</script>
    			{% endfor %}
    			</ul>
		{% else %}
    			<p>No polls are available.</p>
		{% endif %}
		
		<div id="container" style="width:100%; height:400px;"></div>
		<script>
			$(document).ready(function(){
				document.getElementById("demo").innerHTML = "???";
    				var myChart = Highcharts.chart('container', {
        			chart: {
            				type: 'bar'
        			},
        			title: {
            				text: 'Fruit Consumption'
        			},
        			xAxis: {
            				categories: ['Apples', 'Bananas', 'Oranges']
        			},
        			yAxis: {
            				title: {
                				text: 'Fruit eaten'
            				}
        			},
        			series: [{
            				name: 'Jane',
            				data: [1, 0, 4]
        				}, {
            				name: 'John',
            				data: [5, 7, 3]
        				}]
    				});
			});
		</script>
		
	</body>
</html>

polls/templates/polls/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>

polls/templates/polls/test.html
<!DOCTYPE HTML>
<html> 
	<head> 
		<title>Test Chart</title> 
		<script src="http://code.highcharts.com/highcharts.js"></script>
		<script src="http://code.jquery.com/jquery-1.11.0.min.js"></script>
	</head>
	<body> 
		<script>
			var array = new Array(3);
			var index = 0;
		</script>
		{% if test_data %}
    			{% for data in test_data %}
				<script>
					array[index] = parseInt("{{ data }}");
					index += 1; 
				</script>
    			{% endfor %}
    			</ul>
		{% else %}
    			<p>No polls are available.</p>
		{% endif %}
		
		<div id="container" style="width:100%; height:400px;"></div>
		<script>
			$(document).ready(function(){
    				var myChart = Highcharts.chart('container', {
        			chart: {
            				type: 'bar'
        			},
        			title: {
            				text: 'Fruit Consumption'
        			},
        			xAxis: {
            				categories: ['Apples', 'Bananas', 'Oranges']
        			},
        			yAxis: {
            				title: {
                				text: 'Fruit eaten'
            				}
        			},
        			series: [{
            				name: 'Jane',
            				data: array
        				}, {
            				name: 'John',
            				data: [5, 7, 3]
        				}]
    				});
			});
		</script>
		
	</body>
</html>